# Generated by Django 4.2.30 on 2026-08-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('served', models.PositiveIntegerField(default=0)),
                ('cancelled', models.PositiveIntegerField(default=0)),
                ('avg_wait', models.FloatField(default=0.0, help_text="Temps moyen d'attente en minutes")),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='services.service')),
            ],
            options={
                'db_table': 'mt_daily_reports',
                'ordering': ['-date'],
                'unique_together': {('service', 'date')},
            },
        ),
    ]
