# Generated by Django 4.2.30 on 2026-09-19 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def verify_existing_privileged_users(apps, schema_editor):
    """
    Les comptes staff / agent / admin existants ont été créés par un opérateur
    (createsuperuser, seed, admin Django) : on ne les bloque pas. Les usagers
    inscrits avant cette migration devront confirmer leur email (renvoi possible
    depuis l'écran de connexion).
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(
        models.Q(is_staff=True) | models.Q(is_superuser=True) | ~models.Q(role='user')
    ).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="L'utilisateur a confirmé son adresse email.", verbose_name='Email vérifié'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de vérification email',
                'verbose_name_plural': 'Tokens de vérification email',
                'db_table': 'mt_email_verification_tokens',
            },
        ),
        migrations.RunPython(verify_existing_privileged_users, migrations.RunPython.noop),
    ]
