# Generated by Django 5.2.17 on 2026-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_email_verified_and_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, help_text="Rappel par SMS quand le tour de l'usager approche ou arrive.", verbose_name='Recevoir des SMS'),
        ),
    ]
