[project]
name = "montour"
version = "1.0.0"
description = "MonTour - Système intelligent de gestion des files d'attente au Bénin"
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "Django>=5.1,<6.0",
    "djangorestframework>=3.15.1",
    "djangorestframework-simplejwt>=5.3.1",
    "django-cors-headers>=4.3.1",
    "django-filter>=23.5",
    "drf-spectacular>=0.27.1",
    "python-dotenv>=1.0.1",
    "requests>=2.31.0",
    "Pillow>=10.2.0",
    "whitenoise>=6.6.0",
    "gunicorn>=21.2.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
