# Generated by Django 4.2.30 on 2026-08-17 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Santé'), ('admin', 'Administration'), ('finance', 'Finance / Microfinance'), ('agriculture', 'Agriculture'), ('other', 'Autre')], default='other', max_length=20)),
                ('icon', models.CharField(default='🏢', help_text='Emoji représentant le service', max_length=10)),
                ('color', models.CharField(default='#1a73e8', help_text='Couleur hexadécimale', max_length=7)),
                ('avg_service_time', models.PositiveIntegerField(default=10, help_text='Temps moyen de service en minutes')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'mt_services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='services.service')),
            ],
            options={
                'db_table': 'mt_service_hours',
                'ordering': ['day'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='mt_services_categor_677019_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicehours',
            unique_together={('service', 'day')},
        ),
    ]
