# Generated by Django 4.2.30 on 2026-08-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Bot')], default='user', max_length=5)),
                ('intent', models.CharField(blank=True, help_text='Intention Rasa détectée', max_length=50)),
                ('confidence', models.FloatField(default=0.0, help_text='Score de confiance Rasa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message chatbot',
                'verbose_name_plural': 'Messages chatbot',
                'db_table': 'mt_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
