# Generated by Django 4.2.30 on 2026-08-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Numéro attribué dans la file')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('called', 'Appelé'), ('served', 'Servi'), ('cancelled', 'Annulé'), ('missed', 'Absent')], default='waiting', max_length=12)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('senior', 'Senior (60+ ans)'), ('handicap', 'Personne handicapée'), ('urgent', 'Urgence médicale')], default='normal', max_length=10)),
                ('priority_score', models.PositiveIntegerField(default=0, help_text="Score calculé par l'IA pour trier la file")),
                ('estimated_wait', models.PositiveIntegerField(default=0, help_text="Temps d'attente estimé en minutes (IA)")),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('actual_wait', models.PositiveIntegerField(blank=True, help_text='Durée réelle en minutes', null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queues.queue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'mt_tickets',
                'ordering': ['-priority_score', 'requested_at'],
                'indexes': [models.Index(fields=['queue', 'status'], name='mt_tickets_queue_i_5a96cb_idx'), models.Index(fields=['user', 'status'], name='mt_tickets_user_id_0e7b72_idx'), models.Index(fields=['status', 'requested_at'], name='mt_tickets_status_716019_idx')],
            },
        ),
    ]
