# Generated by Django 4.2.30 on 2026-08-17 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée'), ('paused', 'En pause')], default='open', max_length=10)),
                ('current_number', models.PositiveIntegerField(default=0, help_text='Dernier numéro attribué')),
                ('called_number', models.PositiveIntegerField(default=0, help_text='Dernier numéro appelé au guichet')),
                ('max_capacity', models.PositiveIntegerField(default=100, help_text='Capacité maximale de la file')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='services.service')),
            ],
            options={
                'verbose_name': "File d'attente",
                'verbose_name_plural': "Files d'attente",
                'db_table': 'mt_queues',
            },
        ),
    ]
