# Generated by Django 5.2.17 on 2026-09-20 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tickets', '0002_sms_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('approach', 'Tour qui approche'), ('called', 'Tour arrivé'), ('test', 'Test')], max_length=10)),
                ('to', models.CharField(blank=True, max_length=20)),
                ('text', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True, help_text="Motif de l'échec ou de l'abandon")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='tickets.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'db_table': 'mt_sms_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mt_sms_logs_status_63c59d_idx')],
            },
        ),
    ]
